language: python
dist: xenial
sudo: true
os:
  - linux
install: "make"

services:
  - docker

cache: pip

script:
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" != "2.6" ]] ; then make test-readme; fi
  - make ci

jobs:
  include:
    # - stage: lint
    #   script:
    #     - make lint
    #   python: '3.7'
    # - stage: test
    #   script:
    #     - make ci
    #   python: '3.6'
    # - stage: test
    #   script:
    #     - make ci
    #   python: '3.7'
    #   dist: xenial
    # - stage: test
    #   script:
    #     - make ci
    #   python: '3.8'
    #   dist: xenial
    # - stage: coverage
    #   python: '3.7'
    #   script: codecov
    - stage: build-docs
      python: '3.7'
      script: pydocmd build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: _build/site
        fqdn: mbeacom.github.io
        target-branch: gh-pages
        on:
          branch: master
