language: python
dist: xenial
sudo: true
os:
  - linux
install: "make"

services:
  - docker

cache: pip

jobs:
  include:
    - stage: publish
      python: '3.7'
      script:
        - poetry install
        - pydocmd build
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          keep-history: true
          local-dir: _build/site
          target-branch: gh-pages
          on:
            branch: master
        - provider: pypi
          user: $PYPI_USER
          password: $PYPI_PASSWORD
          distributions: "sdist bdist_wheel"
          skip_existing: true
          skip_cleanup: true
          on:
            tags: true
        - provider: releases
          api_key: $GITHUB_TOKEN
          file:
            - "dist/cloudendure-*-py3-none-any.whl"
            - "dist/cloudendure-*.tar.gz"
          on:
            tags: true
