version: "3.7" # https://docs.docker.com/compose/compose-file/compose-versioning/
services:
  app:
    build: .
    image: mbeacom/cloudendure-py:latest
    volumes:
      - .:/app
    deploy:
      replicas: 1
      update_config:
        delay: 10s
      restart_policy:
        condition: on-failure
  stepfunctions:
    image: amazon/aws-stepfunctions-local
    restart: unless-stopped
    ports:
      - "8083:8083"
    deploy:
      replicas: 1
      update_config:
        delay: 10s
      restart_policy:
        condition: on-failure
